// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAdminInfo = "admin_info"

// AdminInfo mapped from table <admin_info>
type AdminInfo struct {
	ID       int64  `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`  // 自增id
	RoleID   int64  `gorm:"column:role_id;type:int;not null" json:"role_id"`             // 角色id
	Username string `gorm:"column:username;type:varchar(12);not null" json:"username"`   // 管理员名字
	Password string `gorm:"column:password;type:varchar(12);not null" json:"password"`   // 管理员密码
	Email    string `gorm:"column:email;type:varchar(64);not null" json:"email"`         // 管理员邮箱
	Status   int8   `gorm:"column:status;type:tinyint;not null;default:1" json:"status"` // 状态位
}

// TableName AdminInfo's table name
func (*AdminInfo) TableName() string {
	return TableNameAdminInfo
}
