// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameInformation = "information"

// Information mapped from table <information>
type Information struct {
	ID            int64     `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`                          // 自增id
	StudentNumber string    `gorm:"column:student_number;type:varchar(12);not null" json:"student_number"`               // 学号
	StudentName   *string   `gorm:"column:student_name;type:varchar(12)" json:"student_name"`                            // 姓名
	MajorClass    *string   `gorm:"column:major_class;type:varchar(12)" json:"major_class"`                              // 专业班级
	Sex           string    `gorm:"column:sex;type:varchar(2);not null" json:"sex"`                                      // 性别
	Qq            string    `gorm:"column:qq;type:varchar(12);not null" json:"qq"`                                       // qq号
	Phone         string    `gorm:"column:phone;type:varchar(11);not null" json:"phone"`                                 // 手机号
	Email         string    `gorm:"column:email;type:varchar(64);not null" json:"email"`                                 // 邮箱
	Year          int64     `gorm:"column:year;type:int;not null" json:"year"`                                           // 报名年份
	LastIP        string    `gorm:"column:last_ip;type:varchar(24);not null" json:"last_ip"`                             // 提交ip
	SignTime      time.Time `gorm:"column:sign_time;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"sign_time"` // 提交时间
	Status        int8      `gorm:"column:status;type:tinyint;not null;default:1" json:"status"`                         // 状态位
}

// TableName Information's table name
func (*Information) TableName() string {
	return TableNameInformation
}
